mischiros_tienda_homepage:
    pattern:  /
    defaults: { _controller: MischirosTiendaBundle:Default:home }

mischiros_tienda_comprarlistar:
    pattern:  /comprar/listar
    defaults: { _controller: MischirosTiendaBundle:Ropa:Listar }