mischiros_tienda_homepage:
    pattern:  /
    defaults: { _controller: MischirosTiendaBundle:Default:home }

mischiros_tienda_comprarpage:
    pattern:  /comprar
    defaults: { _controller: MischirosTiendaBundle:Ropa:comprar }