parameters:
#    mischiros_tienda.example.class: Mischiros\TiendaBundle\Example

services:
#    mischiros_tienda.example:
#        class: %mischiros_tienda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
