<?php

namespace Proxies\__CG__\Mischiros\TiendaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medida extends \Mischiros\TiendaBundle\Entity\Medida implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'hombro', 'pecho', 'cintura', 'cadera', 'tipo', 'talla');
        }

        return array('__isInitialized__', 'id', 'hombro', 'pecho', 'cintura', 'cadera', 'tipo', 'talla');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medida $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHombro($hombro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHombro', array($hombro));

        return parent::setHombro($hombro);
    }

    /**
     * {@inheritDoc}
     */
    public function getHombro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHombro', array());

        return parent::getHombro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPecho($pecho)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPecho', array($pecho));

        return parent::setPecho($pecho);
    }

    /**
     * {@inheritDoc}
     */
    public function getPecho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPecho', array());

        return parent::getPecho();
    }

    /**
     * {@inheritDoc}
     */
    public function setCintura($cintura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCintura', array($cintura));

        return parent::setCintura($cintura);
    }

    /**
     * {@inheritDoc}
     */
    public function getCintura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCintura', array());

        return parent::getCintura();
    }

    /**
     * {@inheritDoc}
     */
    public function setCadera($cadera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCadera', array($cadera));

        return parent::setCadera($cadera);
    }

    /**
     * {@inheritDoc}
     */
    public function getCadera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCadera', array());

        return parent::getCadera();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTalla(\Mischiros\TiendaBundle\Entity\Talla $talla = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTalla', array($talla));

        return parent::setTalla($talla);
    }

    /**
     * {@inheritDoc}
     */
    public function getTalla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTalla', array());

        return parent::getTalla();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(\Mischiros\TiendaBundle\Entity\Tipo $tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

}
