<?php

namespace Proxies\__CG__\Mischiros\TiendaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ingreso extends \Mischiros\TiendaBundle\Entity\Ingreso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'cantidad_comprada', 'valor_unitario', 'fecha_de_ingreso', 'prenda', 'usuarios');
        }

        return array('__isInitialized__', 'id', 'cantidad_comprada', 'valor_unitario', 'fecha_de_ingreso', 'prenda', 'usuarios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ingreso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadComprada($cantidadComprada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadComprada', array($cantidadComprada));

        return parent::setCantidadComprada($cantidadComprada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadComprada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadComprada', array());

        return parent::getCantidadComprada();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorUnitario($valorUnitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorUnitario', array($valorUnitario));

        return parent::setValorUnitario($valorUnitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorUnitario', array());

        return parent::getValorUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaDeIngreso($fechaDeIngreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaDeIngreso', array($fechaDeIngreso));

        return parent::setFechaDeIngreso($fechaDeIngreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaDeIngreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaDeIngreso', array());

        return parent::getFechaDeIngreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenda(\Mischiros\TiendaBundle\Entity\Prenda $prenda = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenda', array($prenda));

        return parent::setPrenda($prenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenda', array());

        return parent::getPrenda();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuario(\Application\Sonata\UserBundle\Entity\User $usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuario', array($usuarios));

        return parent::addUsuario($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuario(\Application\Sonata\UserBundle\Entity\User $usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuario', array($usuarios));

        return parent::removeUsuario($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', array());

        return parent::getUsuarios();
    }

}
