parameters:
#    mischiros_foro.example.class: Mischiros\ForoBundle\Example

services:
#    mischiros_foro.example:
#        class: %mischiros_foro.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
